Algoritmo "combinações"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/5/2022
Var
// Seção de Declarações das variáveis 
   c1, c2:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
         para c1 := 1 ate 3 faca
            Para c2 := 1 ate 3 faca
              Escreval(c1, c2)
            FimPara
         FimPara

Fimalgoritmo