Algoritmo "contaAte10"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/5/2022
Var
// Seção de Declarações das variáveis 
   contador: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
         contador <-0
         Enquanto (contador <= 10) faca
                  EscrevaL(contador)

         FimEnquanto
         EscrevaL("Terminei de contar")
Fimalgoritmo