Algoritmo "Creuza03"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/5/2022
Var
// Seção de Declarações das variáveis 
   F, C: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
         Escreva("Qual é a temperatuda aqui?")
         Leia(F)
         C <- (F - 32) / 1.8
         Escreva("No Brasil estaria ", C:4:2)
Fimalgoritmo