Algoritmo "Creuza04"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/5/2022
Var
// Seção de Declarações das variáveis 
   preco, imposto: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
         Escreva("Qual o preço do produto?")
         Leia(preco)
         imposto <- (preco*60)/100
         Escreva("O imposto será de US$",imposto)
Fimalgoritmo